# Generated by Django 5.0 on 2023-12-30 11:17

import django.db.models.deletion
import hostel.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=hostel.models.category_image_dir_path)),
                ('photo1', models.ImageField(upload_to=hostel.models.category_image_dir_path)),
                ('photo2', models.ImageField(upload_to=hostel.models.category_image_dir_path)),
                ('hostel_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.PositiveBigIntegerField()),
                ('price', models.PositiveBigIntegerField()),
                ('no_of_rooms', models.PositiveIntegerField(default=0)),
                ('no_of_beds', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('high_recommendation', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('no_of_bed_availabe', models.PositiveIntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
