# Generated by Django 5.0 on 2023-12-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
